default_config:

frontend:
  themes: !include_dir_merge_named themes

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.10.0.0/24
    - 172.16.0.0/12
    - 192.168.0.0/16

homeassistant:
  name: Pitangui Composed
  latitude: -23.5505
  longitude: -46.6333
  elevation: 760
  country: BR
  unit_system: metric
  time_zone: America/Sao_Paulo
  currency: BRL
  external_url: http://ha.lab.local
  internal_url: http://ha.lab.local
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1/32
        - ::1/128
        - 10.0.0.0/24    # home LAN
        - 10.10.0.0/24   # lab bridge + VPN clients
      allow_bypass_login: true

recorder:
  purge_keep_days: 14
  commit_interval: 30

logger:
  default: info

mobile_app:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
